version: "3.8"
services:
  api-gateway:
    build: ./api_gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - post-service
      - image-service
    networks:
      - upsnet

  auth-service:
    build: ./auth_service
    ports:
      - "8081:8081"
    networks:
      - upsnet

  post-service:
    build: ./post_service
    ports:
      - "8082:8082"
    networks:
      - upsnet

  image-service:
    build: ./image_service
    ports:
      - "8083:8083"
    networks:
      - upsnet

networks:
  upsnet:
    driver: bridge
