spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**
        - id: post-service
          uri: http://post-service:8082
          predicates:
            - Path=/posts/**

server:
  port: 8080
